---
title: "SOK-1005-Assignment3"
author: "Casper Andresen | 30"
format: pdf
editor: visual
---

```{r}
rm (list = ls())
library(tidyverse)
library(janitor) 
library(lubridate)
library(jsonlite)
```

```{r}
url <- "https://static01.nyt.com/newsgraphics/2021/12/20/us-coronavirus-deaths-2021/ff0adde21623e111d8ce103fedecf7ffc7906264/scatter.json"

df <- fromJSON(url)
```

```{r}
df %>%
  ggplot(aes(x=fully_vaccinated_pct_of_pop, y=deaths_per_100k, label = abbreviate(name, minlength=3))) +
  geom_point(color="#69b3a2", alpha=.6) +
  geom_text(hjust=.5, vjust=-.8, size=2.6) +
  scale_x_continuous(labels = scales::percent) +
  labs(y = "avg. monthly deaths per 100 000", x = "Share of population fully vaccinated", title = "Covid-19 deaths since universal adult vaccine eligibility compared with \nvaccination rates") +
  annotate("segment", x = .59, xend = .58, y = 15.4, yend = 16,
           arrow = arrow(type = "closed", length = unit(0.02, "npc"))) +
  annotate("text", x = .6, y = 14.7, label = "Lower vaccination rates, \nHigher death-rates", size=3) +
  annotate("segment", x = .79, xend = .8, y = 8, yend = 7.4,
           arrow = arrow(type = "closed", length = unit(0.02, "npc"))) +
  annotate("text", x = .755, y = 9, label = "Higher vaccination rate, \nLower death-rates", size=3) +
  theme_bw() +
  geom_smooth(method = lm, color="black")
```

```{r}
lm(df$deaths_per_100k ~ df$fully_vaccinated_pct_of_pop, df)
```
